In [2]:
import numpy as np
import pandas as pd
import io 
from scipy import stats
import pickle
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import label_binarize
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.cluster import DBSCAN, KMeans
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.metrics import recall_score, roc_auc_score

In [5]:
ping_df = pd.read_csv('ping_training_data.csv', delimiter='\t')
voice_df = pd.read_csv('voice_training_data.csv', delimiter='\t')
video_df = pd.read_csv('video_training_data.csv', delimiter='\t')
dns_df = pd.read_csv('dns_training_data.csv', delimiter='\t')
telnet_df = pd.read_csv('telnet_training_data.csv', delimiter='\t')
df = pd.concat([ping_df, voice_df, video_df, dns_df, telnet_df], ignore_index=True)
df = pd.concat([ping_df, voice_df, video_df, dns_df, telnet_df], ignore_index=True)
#df = pd.DataFrame(['data'], columns=['feature_names']); 

print(df)

      Forward Packets Forward Bytes Delta Forward Packets Delta Forward Bytes  \
0              228550      29820143                     0                   0   
1              228550      29820143                     0                   0   
2              228550      29820143                     0                   0   
3              228550      29820143                     0                   0   
4              228551      29820241                     1                  98   
...               ...           ...                   ...                 ...   
26236          126759      13693636                     0                   0   
26237          126759      13693636                     0                   0   
26238          126759      13693636                     0                   0   
26239          126759      13693636                     0                   0   
26240          126759      13693636                     0                   0   

      Forward Instantaneous

In [10]:
df.dropna(inplace=True)

In [16]:
df[df.columns[:-1]] = df[df.columns[:-1]].astype(float)
df['Traffic Type'] = df['Traffic Type'].astype('category')

In [17]:
df['Traffic Type'].value_counts()

telnet    6749
video     6704
ping      6551
voice     6237
Name: Traffic Type, dtype: int64

In [19]:
X= df.drop('Traffic Type', axis=1)
y = df['Traffic Type']


In [20]:
from sklearn import preprocessing

#x = df.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
X = min_max_scaler.fit_transform(X)
X = pd.DataFrame(X)

In [21]:
X_train,X_test,y_train,y_test = train_test_split(X, y, stratify=y, test_size=0.3, random_state=888)

In [22]:
#Entraînement du modèle:Nous allons maintenant créer et entraîner le modèle.
model = LogisticRegression(max_iter=100, penalty='l2', solver='lbfgs', 
                           class_weight='balanced', random_state=10)

In [23]:
model.fit(X_train,y_train)

c:\Users\bachi\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(class_weight='balanced', random_state=10)

In [24]:
predictions = model.predict(X_test)

In [25]:
print('Accuracy: %.2f%%' % (accuracy_score(y_test, predictions)*100))

Accuracy: 89.28%


In [26]:
print(pickle.format_version)

4.0


In [27]:
pickle.dump(model,open('testsigma', 'wb'))

In [28]:
cm = confusion_matrix(y_test, predictions, labels=y.cat.categories)
print(cm)


[[1662    0  304    0]
 [   0 2018    0    7]
 [  21    0 1990    0]
 [   0   14  498 1359]]
